# Generated by Django 5.1.4 on 2025-01-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.CharField(max_length=100)),
                ('date_of_activity', models.DateTimeField()),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
    ]
