# Generated by Django 5.2.4 on 2025-10-05 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='team_car_option',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'no')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 5, 18, 42, 44, 590924)),
        ),
    ]
