# Generated by Django 5.2.4 on 2025-10-06 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0002_activities_team_car_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityphoto',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='gdrive_file_name',
            field=models.CharField(blank=True, help_text='Original file name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='gdrive_web_content_link',
            field=models.URLField(blank=True, help_text='Google Drive direct view link', null=True),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='gdrive_web_view_link',
            field=models.URLField(blank=True, help_text='Google Drive web view link', null=True),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='local_file_path',
            field=models.CharField(blank=True, help_text='Temporary local file path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='gdrive_file_name',
            field=models.CharField(blank=True, help_text='Original file name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='gdrive_web_content_link',
            field=models.URLField(blank=True, help_text='Google Drive direct view link', null=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='gdrive_web_view_link',
            field=models.URLField(blank=True, help_text='Google Drive web view link', null=True),
        ),
        migrations.AddField(
            model_name='activityvideo',
            name='local_file_path',
            field=models.CharField(blank=True, help_text='Temporary local file path', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 6, 2, 36, 49, 777937)),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='activityvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
