# Generated by Django 5.2.4 on 2025-10-06 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0003_activityphoto_gdrive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 6, 2, 44, 23, 264582)),
        ),
    ]
