# Generated by Django 5.1.4 on 2025-01-25 12:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0003_alter_activities_date_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 4, 24, 38, 980567)),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='activities_report.activities'),
        ),
    ]
