# Generated by Django 5.1.4 on 2025-01-25 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0004_alter_activities_date_of_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 4, 51, 32, 186109)),
        ),
    ]
