# Generated by Django 5.1.4 on 2025-01-25 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0005_activities_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='project_section',
            field=models.CharField(choices=[("('section 1-A', 'section 1-A')", "('section 1-A', 'section 1-A')"), ("('section 1-B', 'section 1-B')", "('section 1-B', 'section 1-B')"), ("('section 1-C', 'section 1-C')", "('section 1-C', 'section 1-C')"), ("('Section 2', 'Section 2')", "('Section 2', 'Section 2')"), ("('Calabar section', 'Calabar section')", "('Calabar section', 'Calabar section')"), ("('A-A', 'A-A')", "('A-A', 'A-A')"), ("('A-B', 'A-B')", "('A-B', 'A-B')"), ("('B-A', 'B-A')", "('B-A', 'B-A')"), ("('B-B', 'B-B')", "('B-B', 'B-B')"), ("('B-C', 'B-C')", "('B-C', 'B-C')"), ("('C-A', 'C-A')", "('C-A', 'C-A')"), ("('C-B', 'C-B')", "('C-B', 'C-B')"), ("('C-C', 'C-C')", "('C-C', 'C-C')")], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('Barrier base', 'Barrier base'), ('Installation of jersey separation barrier', 'Installation of jersey separation barrier'), ('Installation CRCP', 'Installation CRCP'), ('Installation stoneBase', 'Installation stoneBase'), ('Installation subBase', 'Installation subBase'), ('Installation soil cement', 'Installation soil cement'), ('Steel structure', 'Steel structure'), ('Concrete work', 'Concrete work'), ('Pipe factory', 'Pipe factory'), ('Batching plant', 'Batching plant'), ('Conduct a survey', 'Conduct a survey'), ('Create road design plans', 'Create road design plans'), ('Cut elevations', 'Cut elevations'), ('Fill elevations', 'Fill elevations'), ('Dredging elevations', 'Dredging elevations'), ('Clearing elevations', 'Clearing elevations'), ('Levelling and handling surveying instruments', 'Levelling and handling surveying instruments'), ('Hitech activity report', 'Hitech activity report'), ('Road requirements boundary', 'Road requirements boundary'), ('Toe', 'Toe'), ('Top of stoneBase', 'Top of stoneBase'), ('Top of subBase', 'Top of subBase'), ('Top of CRCP', 'Top of CRCP'), ('Borehole', 'Borehole'), ('Other', 'Other'), ('Clearing obstacles', 'Clearing obstacles'), ('Grade prepare road', 'Grade prepare road'), ('Excavate road width', 'Excavate road width'), ('Excavate unsuitable materials', 'Excavate unsuitable materials'), ('Compaction subgrade', 'Compaction subgrade'), ('Excavate for pipe 600mm', 'Excavate for pipe 600mm'), ('Blinding for pipe 600mm', 'Blinding for pipe 600mm'), ('Blinding for discharge 900mm', 'Blinding for discharge 900mm'), ('Blinding for discharge 1200mm', 'Blinding for discharge 1200mm'), ('Excavate for discharge 900mm', 'Excavate for discharge 900mm'), ('Excavate for discharge 1200mm', 'Excavate for discharge 1200mm'), ('Excavate for culvert 150*150', 'Excavate for culvert 150*150'), ('Excavate for culvert 200*200', 'Excavate for culvert 200*200'), ('Blinding culvert 150*150', 'Blinding culvert 150*150'), ('Blinding for culvert 200*200', 'Blinding for culvert 200*200'), ('Base culvert 150*150', 'Base culvert 150*150'), ('Base for culvert 200*200', 'Base for culvert 200*200'), ('Complete drainage', 'Complete drainage'), ('Entrance slab', 'Entrance slab'), ('Excavate drainage', 'Excavate drainage'), ('Line drainage', 'Line drainage'), ('Culvert cross drainage', 'Culvert cross drainage'), ('Ducts for electrical cables', 'Ducts for electrical cables'), ('Ducts for telecom cable', 'Ducts for telecom cable'), ('Ducts for drinking water pipe', 'Ducts for drinking water pipe'), ('Lay layer subbase', 'Lay layer subbase'), ('Compact subbase', 'Compact subbase'), ('Soil cement stabilization', 'Soil cement stabilization'), ('Lay layer basecourse', 'Lay layer basecourse'), ('Compact basecourse', 'Compact basecourse'), ('Building', 'Building'), ('Other (fans, walls, etc.)', 'Other (fans, walls, etc.)'), ('Apply asphalt concrete', 'Apply asphalt concrete'), ('Compact asphalt concrete', 'Compact asphalt concrete'), ('Construct sidewalks and shoulders', 'Construct sidewalks and shoulders'), ('Paint road marks', 'Paint road marks'), ('Install traffic signs and signals', 'Install traffic signs and signals'), ('Plant grass or vegetation to prevent erosion', 'Plant grass or vegetation to prevent erosion'), ('Implement landscaping elements to beautify', 'Implement landscaping elements to beautify'), ('Ensure compliance with design specifications and safety standards', 'Ensure compliance with design specifications and safety standards'), ('Quality control test materials', 'Quality control test materials')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 9, 56, 35, 765650)),
        ),
    ]
