# Generated by Django 5.1.4 on 2025-01-25 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0006_activities_project_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 10, 6, 47, 795245)),
        ),
    ]
