# Generated by Django 5.1.4 on 2025-01-25 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0007_alter_activities_date_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 10, 15, 27, 49234)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='project_section',
            field=models.CharField(choices=[('section 1-A', 'section 1-A'), ('section 1-B', 'section 1-B'), ('section 1-C', 'section 1-C'), ('Section 2', 'Section 2'), ('Calabar section', 'Calabar section'), ('A-A', 'A-A'), ('A-B', 'A-B'), ('B-A', 'B-A'), ('B-B', 'B-B'), ('B-C', 'B-C'), ('C-A', 'C-A'), ('C-B', 'C-B'), ('C-C', 'C-C')], max_length=100, null=True),
        ),
    ]
