# Generated by Django 5.1.4 on 2025-01-26 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_report', '0008_alter_activities_date_of_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='fullname',
            field=models.CharField(choices=[('MATTHEW EMEKA', 'MATTHEW EMEKA'), ('JOHN BOGHA', 'JOHN BOGHA'), ('GABRIEL ANYIN UDE', 'GABRIEL ANYIN UDE'), ('ADEBAYO WILLIAMS', 'ADEBAYO WILLIAMS'), ('ADEWUYI ADEDIRE', 'ADEWUYI ADEDIRE'), ('MICHAEL NWANKWO', 'MICHAEL NWANKWO'), ('CLEMENT JOHN', 'CLEMENT JOHN'), ('OYEBOADE OLAYIDE TIMOTHY', 'OYEBOADE OLAYIDE TIMOTHY'), ('AZUBUIKE PRINCE', 'AZUBUIKE PRINCE'), ('NWIDUM JAMES', 'NWIDUM JAMES'), ('OLULADE TOMIWA', 'OLULADE TOMIWA'), ('STEPHEN BENJAMIN', 'STEPHEN BENJAMIN'), ('MOJEED OLUMIDE', 'MOJEED OLUMIDE'), ('DUROJAYE SUNDAY', 'DUROJAYE SUNDAY'), ('OLUWATOBI SAMUEL', 'OLUWATOBI SAMUEL'), ('GABRIEL', 'GABRIEL'), ('JIMOH KABIR', 'JIMOH KABIR'), ('Tobe', 'Tobe'), ('NWACHUKWU CHIJIOKE', 'NWACHUKWU CHIJIOKE'), ('ABU BAKER', 'ABU BAKER'), ('Stanley Okpetu', 'Stanley Okpetu'), ('Oluwagbemiro Temidayo Stephen', 'Oluwagbemiro Temidayo Stephen'), ('Olaniyi', 'Olaniyi'), ('Alex', 'Alex'), ('Hassan', 'Hassan'), ('AYO', 'AYO'), ('Believe', 'Believe'), ('TONY', 'TONY'), ('BUKOLA', 'BUKOLA'), ('ADERONKE', 'ADERONKE'), ('SODIQ', 'SODIQ'), ('TONY', 'TONY'), ('Habib', 'Habib'), ('Abdulazeez', 'Abdulazeez'), ('Celestino', 'Celestino')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='role',
            field=models.CharField(choices=[('PRO', 'PRO'), ('Surveyor', 'Surveyor'), ('Chain Boy', 'Chain Boy'), ('Excavator Operator', 'Excavator Operator'), ('Dozer Operator', 'Dozer Operator'), ('Driver', 'Driver'), ('Securities', 'Securities'), ('Forman', 'Forman'), ('Roller Operator', 'Roller Operator'), ('Mechanic', 'Mechanic'), ('Electrician', 'Electrician'), ('Grader Operator', 'Grader Operator'), ('Swamp buggy operator', 'Swamp buggy operator'), ('Canoe operator', 'Canoe operator'), ('Engineer', 'Engineer')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='subcontractor_name',
            field=models.CharField(choices=[('Zenith', 'Zenith'), ('SPG', 'SPG'), ('Multi road', 'Multi road')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='team_car',
            field=models.CharField(choices=[('NISSAN (KRD-704-YG) BLACK', 'NISSAN (KRD-704-YG) BLACK'), ('TOYOTA RENTAL (EPE-938GY)', 'TOYOTA RENTAL (EPE-938GY)'), ('TOYOTA RENTAL (EPE-939GY)', 'TOYOTA RENTAL (EPE-939GY)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_of_activity',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 2, 50, 23, 342990)),
        ),
    ]
